### ISSUE TITLE
Ошибка в нейминге

### ISSUE THREAD

**Issue by igosheva** [S5477/loft#12]
https://github.com/S5477/loft/blob/d318ad791e70d2381f8d81cd4f3c2f4db79038ad/comments.html#L22

**Comment by igosheva** [comment]
Через "_" именуются модификаторы, а тебе нужен класс элемента - header-logo__link

**Comment by igosheva** [comment]
И добавить для ссылки dipslay

**Comment by S5477** [comment]
Сделано
