### ISSUE TITLE
Убрать фиксированную высоту, обнулить у внутренних элементов margin, который им добавляет браузер, оттолкнуть внутренние элементы за счет паддинга  у popup

### ISSUE THREAD

**Issue by igosheva** [S5477/loft#14]
https://github.com/S5477/loft/blob/d318ad791e70d2381f8d81cd4f3c2f4db79038ad/comments.html#L28

**Comment by igosheva** [comment]
И выравнять внутри элементы по одной линии http://joxi.ru/L21dao3t6aKRnm

**Comment by S5477** [comment]
Сделано
